RDKB-42751 : Upflow platform specific CCSP patches.
Reason for change:as part of clean up patche activity.

Test Procedure:tested

Risks: None
Signed-off-by: Ankur Adroja <Ankur_Adroja@comcast.com>
(cherry picked from commit 35145b0c8f366106a89950e9331999429474529d)

RDKCOM-3327: REFPLTB-1845 Build error in CcspPsm, missing UNREFERENCED_PARAM...

Reason for change:
Build error in CcspPsm with missing UNREFERENCED_PARAMETER:
| CcspPsm/source/Ssp/psm_hal_apis.c:701:5: error: implicit declaration of function UNREFERENCED_PARAMETER [-Werror=implicit-function-declaration]
|   701 |     UNREFERENCED_PARAMETER(params);
|       |     ^~~~~~~~~~~~~~~~~~~~~~
| cc1: all warnings being treated as errors
| Makefile:699: recipe for target Ssp/PsmSsp-psm_hal_apis.o failed
This is introduced by
https://code.rdkcentral.com/r/c/rdkb/components/opensource/ccsp/CcspPsm/+/75662

Test Procedure: None.
Risks: Low.
Signed-off-by: Stephen Barrett <stephen_barrett@comcast.com>

RDKB-44882 : Compliance Issues in CcspPsm Change

Reason for change: because of LnF passphrase exposed

Test Procedure:
1.Verify LnF WiFi

Risks: None
Signed-off-by: Ankur Adroja <Ankur_Adroja@comcast.com>

Change-Id: I52d9b8ba4d73d68ac4b7f44292113c476231f293