RDKCOM-1939 RDKBCMF-254 CcspPsm build errors
CMF builds are failing when all warnings are treated as errors in
meta-rdk-broadband/52099.
../../../../../../../../rdkb/components/opensource/ccsp/CcspPsm/source/Ssp/psm_hal_apis.c: In function 'PsmHal_GetCustomParams':
../../../../../../../../rdkb/components/opensource/ccsp/CcspPsm/source/Ssp/psm_hal_apis.c:101:45: error: unused parameter 'params' [-Werror=unused-parameter]
 int PsmHal_GetCustomParams( PsmHalParam_t **params, int *cnt)
                                             ^~~~~~
../../../../../../../../rdkb/components/opensource/ccsp/CcspPsm/source/Ssp/psm_hal_apis.c:101:58: error: unused parameter 'cnt' [-Werror=unused-parameter]
 int PsmHal_GetCustomParams( PsmHalParam_t **params, int *cnt)
                                                          ^~~

Reason for change: RDKBCMF-254 CcspPsm build errors
Test Procedure: None.
Risks: Low.
Signed-off-by: Stephen Barrett <stephen.barrett@accenture.com>

(cherry picked from commit 2dc3949b34aefcbd40bca4c40d76874f8f99e436)
(cherry picked from commit 4f71a88bf0a6f5886614856cfcdda96ec0303667)
Change-Id: Ie1da25515f904ed1969252b222d440845e5129ce